"""Chat 1 domain/application baseline for MREA Project & Guided Capture."""

from .artifacts import ArtifactNotFoundError, FileSystemArtifactStore
from .calibration import (
    CalibrationDetectionError,
    CalibrationService,
    OpenCvCharucoCalibrationDetector,
)
from .contracts import CanonicalContractBuilder, CanonicalContractError
from .lineage import (
    CaptureLineageError,
    active_clean_reference,
    calibration_for_active_reference,
    measurement_frames_for_active_reference,
    rectification_for_active_reference,
)
from .history import (
    CaptureAttemptHistoryError,
    CaptureAttemptHistoryService,
    CaptureAttemptSnapshot,
    CaptureViewAttemptHistory,
)
from .guidance import (
    GuidedCaptureAction,
    GuidedCaptureBlockerCode,
    GuidedCaptureError,
    GuidedCapturePolicy,
    GuidedCaptureReadiness,
    GuidedCaptureReadinessService,
    GuidedViewReadiness,
)
from .models import (
    ArtifactRecord,
    CalibrationResult,
    CameraMetadata,
    CaptureQualityFinding,
    CaptureQualityMetrics,
    CaptureQualityResult,
    CaptureQualityVerdict,
    CapturePlan,
    CapturePlanItem,
    CaptureSession,
    CaptureViewProgress,
    CaptureViewRevisionEvent,
    CaptureViewStatus,
    CaptureViewType,
    FrameKind,
    FrameRecord,
    MeasurementMatProfile,
    PartContext,
    Project,
    ProjectStatus,
    QualityReasonCode,
    QualitySeverity,
    RectifiedReferenceRecord,
    VoiceCaptureCommand,
    VoiceCaptureEvent,
)
from .quality import (
    CaptureQualityAnalyzer,
    CaptureQualityError,
    CaptureQualityPolicy,
    CaptureQualityService,
    OpenCvCaptureQualityAnalyzer,
    RussianQualityGuidanceAdapter,
)
from .quality_lifecycle import (
    CaptureQualityLifecycleError,
    CaptureQualityLifecycleService,
)
from .rectification import (
    OpenCvPerspectiveNormalizer,
    PerspectiveNormalizer,
    RectificationError,
    RectificationService,
    RectifiedRaster,
)
from .repositories import (
    CaptureSessionNotFoundError,
    JsonCaptureSessionRepository,
    JsonProjectRepository,
    ProjectNotFoundError,
)
from .services import (
    CapturePlanService,
    CaptureSessionService,
    CaptureWorkflowError,
    ProjectService,
)

__all__ = [
    "ArtifactNotFoundError",
    "ArtifactRecord",
    "CalibrationDetectionError",
    "CalibrationResult",
    "CalibrationService",
    "CameraMetadata",
    "CaptureQualityAnalyzer",
    "CaptureQualityError",
    "CaptureQualityFinding",
    "CaptureQualityLifecycleError",
    "CaptureQualityLifecycleService",
    "CaptureQualityMetrics",
    "CaptureQualityPolicy",
    "CaptureQualityResult",
    "CaptureQualityService",
    "CaptureQualityVerdict",
    "CaptureAttemptHistoryError",
    "CaptureAttemptHistoryService",
    "CaptureAttemptSnapshot",
    "CaptureLineageError",
    "CanonicalContractBuilder",
    "CanonicalContractError",
    "CapturePlan",
    "CapturePlanItem",
    "CapturePlanService",
    "CaptureSession",
    "CaptureSessionNotFoundError",
    "CaptureSessionService",
    "CaptureViewAttemptHistory",
    "CaptureViewProgress",
    "CaptureViewRevisionEvent",
    "CaptureViewStatus",
    "CaptureViewType",
    "CaptureWorkflowError",
    "FileSystemArtifactStore",
    "FrameKind",
    "FrameRecord",
    "GuidedCaptureAction",
    "GuidedCaptureBlockerCode",
    "GuidedCaptureError",
    "GuidedCapturePolicy",
    "GuidedCaptureReadiness",
    "GuidedCaptureReadinessService",
    "GuidedViewReadiness",
    "JsonCaptureSessionRepository",
    "JsonProjectRepository",
    "MeasurementMatProfile",
    "OpenCvCharucoCalibrationDetector",
    "OpenCvCaptureQualityAnalyzer",
    "OpenCvPerspectiveNormalizer",
    "PartContext",
    "PerspectiveNormalizer",
    "Project",
    "ProjectNotFoundError",
    "ProjectService",
    "ProjectStatus",
    "QualityReasonCode",
    "QualitySeverity",
    "RussianQualityGuidanceAdapter",
    "RectificationError",
    "RectificationService",
    "RectifiedRaster",
    "RectifiedReferenceRecord",
    "VoiceCaptureCommand",
    "VoiceCaptureEvent",
    "active_clean_reference",
    "calibration_for_active_reference",
    "measurement_frames_for_active_reference",
    "rectification_for_active_reference",
]
