"""Chat 1 domain/application baseline for MREA Project & Guided Capture."""

from .artifacts import ArtifactNotFoundError, FileSystemArtifactStore
from .calibration import (
    CalibrationDetectionError,
    CalibrationService,
    OpenCvCharucoCalibrationDetector,
)
from .contracts import CanonicalContractBuilder, CanonicalContractError
from .models import (
    ArtifactRecord,
    CalibrationResult,
    CameraMetadata,
    CaptureQualityFinding,
    CaptureQualityMetrics,
    CaptureQualityResult,
    CaptureQualityVerdict,
    CapturePlan,
    CapturePlanItem,
    CaptureSession,
    CaptureViewProgress,
    CaptureViewStatus,
    CaptureViewType,
    FrameKind,
    FrameRecord,
    MeasurementMatProfile,
    PartContext,
    Project,
    ProjectStatus,
    QualityReasonCode,
    QualitySeverity,
    RectifiedReferenceRecord,
)
from .quality import (
    CaptureQualityAnalyzer,
    CaptureQualityError,
    CaptureQualityPolicy,
    CaptureQualityService,
    OpenCvCaptureQualityAnalyzer,
    RussianQualityGuidanceAdapter,
)
from .rectification import (
    OpenCvPerspectiveNormalizer,
    PerspectiveNormalizer,
    RectificationError,
    RectificationService,
    RectifiedRaster,
)
from .repositories import (
    CaptureSessionNotFoundError,
    JsonCaptureSessionRepository,
    JsonProjectRepository,
    ProjectNotFoundError,
)
from .services import (
    CapturePlanService,
    CaptureSessionService,
    CaptureWorkflowError,
    ProjectService,
)

__all__ = [
    "ArtifactNotFoundError",
    "ArtifactRecord",
    "CalibrationDetectionError",
    "CalibrationResult",
    "CalibrationService",
    "CameraMetadata",
    "CaptureQualityAnalyzer",
    "CaptureQualityError",
    "CaptureQualityFinding",
    "CaptureQualityMetrics",
    "CaptureQualityPolicy",
    "CaptureQualityResult",
    "CaptureQualityService",
    "CaptureQualityVerdict",
    "CanonicalContractBuilder",
    "CanonicalContractError",
    "CapturePlan",
    "CapturePlanItem",
    "CapturePlanService",
    "CaptureSession",
    "CaptureSessionNotFoundError",
    "CaptureSessionService",
    "CaptureViewProgress",
    "CaptureViewStatus",
    "CaptureViewType",
    "CaptureWorkflowError",
    "FileSystemArtifactStore",
    "FrameKind",
    "FrameRecord",
    "JsonCaptureSessionRepository",
    "JsonProjectRepository",
    "MeasurementMatProfile",
    "OpenCvCharucoCalibrationDetector",
    "OpenCvCaptureQualityAnalyzer",
    "OpenCvPerspectiveNormalizer",
    "PartContext",
    "PerspectiveNormalizer",
    "Project",
    "ProjectNotFoundError",
    "ProjectService",
    "ProjectStatus",
    "QualityReasonCode",
    "QualitySeverity",
    "RussianQualityGuidanceAdapter",
    "RectificationError",
    "RectificationService",
    "RectifiedRaster",
    "RectifiedReferenceRecord",
]
